create table `participants` (
`ppt_id` int(11) not null auto_increment,
`ppt_first_nm` varchar(255) not null,
`ppt_last_nm` varchar(255),
`ppt_phone_no` varchar(255),
`addr_line_1` varchar(255),
`addr_line_2` varchar(255),
`addr_city` varchar(255),
`addr_state` varchar(255),
`addr_zip` varchar(255),
`referred_by` varchar(255),
`future_contact` varchar(5),
`partner_interest` varchar(5),
`partner_first_nm` varchar(255),
`partner_last_nm` varchar(255),
`partner_phone_no` varchar(255),
`partner_email` varchar(255),
`english_check` varchar(255),
`ppt_age` int(3),
`partner_age` int(3),
`married_flag` varchar(5),
`rel_length` int(10),
`living_together` varchar(5),
`living_together_length` int(10),
`ppt_daily_pain` varchar(5),
`ppt_pain_length` int(10),
`ppt_pain_location` varchar(255),
`ppt_pain_level` int(2),
`ppt_pain_interference` int(2),
`partner_daily_pain` varchar(5),
`partner_pain_length` int(10),
`partner_pain_location` varchar(255),
`partner_pain_level` int(2),
`partner_pain_interference` int(2),
primary key (`ppt_id`)
) engine=innodb;