create table super_study.options (
`option_id` int(11) not null auto_increment,
`field_nm` varchar(255),
`option_nm` varchar(255),
`option_text` varchar(255),
primary key (`option_id`)
) engine=innodb;

insert into super_study.options
(field_nm, option_nm, option_text)
values
("referred_by","academica","Academica"),
("referred_by","craigslist","Craigslist"),
("referred_by","div38","Div38 Listserv"),
("referred_by","facebook","Facebook"),
("referred_by","flyer","Flyer"),
("referred_by","prp","HBEC PRP"),
("referred_by","lunch_and_learn","HBEC Lunch and Learn Event"),
("referred_by","direct_recruitment","DMC Direct Recruitment"),
("referred_by","mpal","Michigan Psychological Association Listserv"),
("referred_by","lab","The Relationships & Health Lab contacted me"),
("referred_by","twitter","Twitter"),
("referred_by","other","Other"),
("future_contact","yes","Yes"),
("future_contact","no","No"),
("future_contact_method","email","Email"),
("future_contact_method","phone","Phone"),
("future_contact_method","mail","Mail"),
("partner_interest","yes","Yes"),
("partner_interest","no","No"),
("english_check","yes","Yes"),
("english_check","no","No"),
("married_flag","yes","Yes"),
("married_flag","no","No"),
("living_together","yes","Yes"),
("living_together","no","No"),
("ppt_daily_pain","yes","Yes"),
("ppt_daily_pain","no","No"),
("ppt_pain_level","0","0"),
("ppt_pain_level","1","1"),
("ppt_pain_level","2","2"),
("ppt_pain_level","3","3"),
("ppt_pain_level","4","4"),
("ppt_pain_level","5","5"),
("ppt_pain_level","6","6"),
("ppt_pain_level","7","7"),
("ppt_pain_level","8","8"),
("ppt_pain_level","9","9"),
("ppt_pain_level","10","10"),
("ppt_pain_interference","0","0"),
("ppt_pain_interference","1","1"),
("ppt_pain_interference","2","2"),
("ppt_pain_interference","3","3"),
("ppt_pain_interference","4","4"),
("ppt_pain_interference","5","5"),
("ppt_pain_interference","6","6"),
("ppt_pain_interference","7","7"),
("ppt_pain_interference","8","8"),
("ppt_pain_interference","9","9"),
("ppt_pain_interference","10","10"),
("partner_daily_pain","yes","Yes"),
("partner_daily_pain","no","No");
				
				