drop table super_study.participants;
drop table super_study.participants_temp;

create table super_study.participants_temp (
`ppt_id` int(11) not null auto_increment,
`ppt_first_nm` varchar(255),
`ppt_last_nm` varchar(255),
`ppt_cell_phone_no` varchar(255),
`ppt_home_phone_no` varchar(255),
`ppt_email` varchar(255),
`addr_line_1` varchar(255),
`addr_line_2` varchar(255),
`addr_city` varchar(255),
`addr_state` varchar(255),
`addr_zip` varchar(255),
`referred_by` varchar(255),
`referred_by_other` varchar(255),
`future_contact` varchar(5),
`future_contact_method` varchar(255),
`partner_interest` varchar(5),
`partner_first_nm` varchar(255),
`partner_last_nm` varchar(255),
`partner_cell_phone_no` varchar(255),
`partner_home_phone_no` varchar(255),
`partner_email` varchar(255),
`english_check` varchar(255),
`ppt_age` int(3),
`partner_age` int(3),
`married_flag` varchar(5),
`rel_length` int(10),
`living_together` varchar(5),
`living_together_length` int(10),
`ppt_daily_pain` varchar(5),
`ppt_pain_length` int(10),
`ppt_pain_location` varchar(255),
`ppt_pain_level` int(2),
`ppt_pain_interference` int(2),
`ppt_pain_type` varchar(255),
`partner_daily_pain` varchar(5),
`partner_pain_length` int(10),
`partner_pain_location` varchar(255),
`partner_pain_level` int(2),
`partner_pain_interference` int(2),
`partner_pain_type` varchar(255),
`completed_screen` varchar(5),
`num_contacts` int(10),
`ineligible_no_full_screen` varchar(5),
`ineligible_no_full_screen_reason` varchar(255),
`disinterest` varchar(5),
`disinterest_reason` varchar(255),
`eligibility_status` varchar(5),
primary key (`ppt_id`)
) engine=innodb;

create table super_study.participants (
`ppt_id` int(11) not null auto_increment,
`ppt_first_nm` varchar(255),
`ppt_last_nm` varchar(255),
`ppt_cell_phone_no` varchar(255),
`ppt_home_phone_no` varchar(255),
`ppt_email` varchar(255),
`addr_line_1` varchar(255),
`addr_line_2` varchar(255),
`addr_city` varchar(255),
`addr_state` varchar(255),
`addr_zip` varchar(255),
`referred_by` varchar(255),
`referred_by_other` varchar(255),
`future_contact` varchar(5),
`future_contact_method` varchar(255),
`partner_interest` varchar(5),
`partner_first_nm` varchar(255),
`partner_last_nm` varchar(255),
`partner_cell_phone_no` varchar(255),
`partner_home_phone_no` varchar(255),
`partner_email` varchar(255),
`english_check` varchar(255),
`ppt_age` int(3),
`partner_age` int(3),
`married_flag` varchar(5),
`rel_length` int(10),
`living_together` varchar(5),
`living_together_length` int(10),
`ppt_daily_pain` varchar(5),
`ppt_pain_length` int(10),
`ppt_pain_location` varchar(255),
`ppt_pain_level` int(2),
`ppt_pain_interference` int(2),
`ppt_pain_type` varchar(255),
`partner_daily_pain` varchar(5),
`partner_pain_length` int(10),
`partner_pain_location` varchar(255),
`partner_pain_level` int(2),
`partner_pain_interference` int(2),
`partner_pain_type` varchar(255),
`completed_screen` varchar(5),
`num_contacts` int(10),
`ineligible_no_full_screen` varchar(5),
`ineligible_no_full_screen_reason` varchar(255),
`disinterest` varchar(5),
`disinterest_reason` varchar(255),
`eligibility_status` varchar(5),
primary key (`ppt_id`)
) engine=innodb;
